package hibernate.Entity;
// Generated Nov 24, 2020 3:23:44 PM by Hibernate Tools 4.3.1



/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Double price;
     private Integer quantity;

    public Items() {
    }

    public Items(String name, Double price, Integer quantity) {
       this.name = name;
       this.price = price;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


